### ISSUE TITLE
Can't login with the username I created.

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#12]
Idk if I'm doing something wrong. 

What I know is that yesterday I extracted LingLibre to a location in my PC, I ran it and registered an user, then I started adding texts to it.

Today I turned the computer on, launched LingLibre and it is not recognizing the username I registered yesterday.
![image](https://user-images.githubusercontent.com/15344931/119259605-639a8100-bba5-11eb-9fd5-0ae4209c60b6.png)
![image](https://user-images.githubusercontent.com/15344931/119259613-6a28f880-bba5-11eb-8868-dd9e62266c71.png)

I'd also like to know where the user data is stored, so I can possibly back it up.

**Comment by ezxpro** [comment]
Well, I recreated the username and restarted the PC, and now everything is in its right place.
![image](https://user-images.githubusercontent.com/15344931/119259746-0ce17700-bba6-11eb-9148-5f0a472568a7.png)
Most likely, I deleted LingLibre's data somehow, especially if it stored things into the %TMP% directory, which I cleaned yesterday.

I'd really like to know where it stores the data, bc I looked into the AppData folder and found nothing, so I'm assuming it created it inside the folder where it's stored.

**Comment by gustavklopp** [comment]
It's easy!
You must login with the administrator account: 
Launch the program but in the tab browser which has opened, change the url to: http://127.0.0.1:8000/admin/login/?next=/admin/
Then name is: lingl /password is: lingl
![Zaslonska slika 2021-05-23 16-46-29](https://user-images.githubusercontent.com/6438275/119265322-8f8a2680-bbe6-11eb-8534-ed9766dd766b.png)
On the left column, you can click on "Users" to see all the users. 
You can verify that the user is still there. (You can't see the password though since they are hashed by security).

**Comment by ezxpro** [comment]
Well, my bad, I had created the user I talked about within an installation I made in a virtual environment
