### ISSUE TITLE
Question about repository age

### ISSUE THREAD

**Issue by ezxpro** [gustavklopp/LingL#29]
Simply put, I'm reporting a bug to GitHub because their website is displaying weird dates on releases and commits ( for example, your releases from 8 days ago show up as being 1 month old here).

So I wanted to confirm the age of the first commits in this repo, see: 
![image](https://user-images.githubusercontent.com/15344931/123027380-20a21800-d3b4-11eb-9e0b-c9c67079024a.png)
![image](https://user-images.githubusercontent.com/15344931/123027387-24359f00-d3b4-11eb-8b14-bf6ca3580eb5.png)

So according to it, your first commits in this repo happened 4 years ago. Your other repos all show up as being at least 6 years old, so I'd like to know about that too.

Thanks.

**Comment by ezxpro** [comment]
As a side note, do you have any recommendation of a good (written) python 3 tutorial? 

I'm learning it from the official documentation's tutorial, but I find it's full with unimportant info (even jokes btw) and the language is not always clear.

If you know about some (written) good learning resources, please refer it to me, thanks.

**Comment by gustavklopp** [comment]
> Simply put, I'm reporting a bug to GitHub because their website is displaying weird dates on releases and commits ( for example, your releases from 8 days ago show up as being 1 month old here).

Because Github sets date on the date of the **creation** of the release, and not when you're **updating** the release. I could create new releases each time but it would end up like hundreds of stored releases (since I'm releasing triple releases for Linux/Win/Mac sometimes several times a week) which make no sense to me, that's why I prefer simply updating them.

And the project LingL is indeed quite old! I've left aside for years but with the pandemic and more free time, I've decided to revive this project..

As for python learning, it's like learning language: The best way to learn is to practice: that's the principle of Lingl!
Choose a program that you'd like to create or contribute to ones you like (LingL may be too a bit too complicated if you've never ever programed though: But you can still have a look, there's lot of comments inside the code)

**Comment by ezxpro** [comment]
Ah, okay, I thought it was a bug.

Btw, thanks for the advice. I'm learning Python out of necessity, not as a hobby or for fun, so practice is becoming an inherent part of it.

Closing this issue, thanks.
