### ISSUE TITLE
Filter 'Last time open' applied inconsistently

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#4]
Filter 'Last time open' works differently :
-  if no time chosen after text list is first opened then all texts are displayed.
-  if no time chosen after unchecking any item in the filter then no text is displayed.

After opening text list page:
![image](https://user-images.githubusercontent.com/7547394/116896883-55f47a00-ac3d-11eb-968d-d6e3c53f0319.png)

After clicking on checkbox beside text '< 1 month ago' and unchecking it again:
![image](https://user-images.githubusercontent.com/7547394/116897009-79b7c000-ac3d-11eb-8281-bfbd5ec045f9.png)

As a user, I never want everything to be filtered out, so the first option (to display all texts) would be preferable.

**Comment by gustavklopp** [comment]
The problem was that, by default, when first opening LingL, all "last time open" were unselected. 
I've changed to the opposite in the last commit. Now, unselecting all "last time open" filter should be a rare event so this warning message should happen very frequently.
 
And it's consistent with the "language" and "Text tags" filter above. You can try it (use the demo for ex.), but it seems very strange if this filter behaves differently from "last time open" filter.

**Comment by m-cote** [comment]
I wouldn't say I'm a big fan of empty lists, but at least consistency is restored! Now 'Last time open' filter always does the same thing when given the same inputs.
