### ISSUE TITLE
To Do counter does not take into account repeated words

### ISSUE THREAD

**Issue by m-cote** [gustavklopp/LingL#6]
The TO DO counter counts the number of words, without taking into account the fact that the same word can occur several times in the text and it needs to be processed only once.
To demonstrate this issue:

1. create a new English text with the following content:
`A A A`
and click `save`
![image](https://user-images.githubusercontent.com/7547394/117001980-aa563300-aceb-11eb-9b27-d0f3ea621161.png)
2. Click read icon on created text
To Do counter says 3
expected 1
![image](https://user-images.githubusercontent.com/7547394/117002154-dc679500-aceb-11eb-8237-db82bcae19c7.png)

**Comment by m-cote** [comment]
on a related note: not sure is it intended behavior or not, but the same term is being saved multiple times.
If I open the term list it would contain one record for each occurrence of a word in the text.
![image](https://user-images.githubusercontent.com/7547394/117003435-87c51980-aced-11eb-91de-0aacc3bafcbb.png)

**Comment by gustavklopp** [comment]
these 2 questions are indeed related:
1. For the last question: those are different words in fact (the column 'id' represents their location in the text). We can dynamically change what is considered as similar (look at the column "similar words". In fact, it's important to separate these words because they potentially can be spelled differently if we want. or conversely, be written the same but having different meaning).
2. for the first question: In fact, in LingL, "similarity" goes beyond words which are spelled the same: for example, "kaufen", "kaufst" etc... can be made "similar". And conversely, words written the same can be made different (especially if they are in compound word: the "ver" in "ver+sterben", "ver+kaufen"). 
That's why I think it's better to keep the simple gross count of unknown words, because only counting words distinct by their spelling would give a false number: "kauftst', "kaufen" etc... are the same, they are not 2 different unknown words. And conversely, words written the same could have different meaning and so are different (especially in compound words).

**Comment by m-cote** [comment]
What is the purpose for saving each occurrence of the same term as a separate row? Each time I edit some term _every single row_ created with this term gets changed in the same way (you can see it on screen 2). 

> In fact, it's important to separate these words because they potentially can be spelled differently if we want.

I don't mind having a row for each distinct spelling. But in this example they are not spelled differently, the spelling is exactly the same and the rows contain exactly the same info.

>  or conversely, be written the same but having different meaning

In a dictionary I can look up a word by it's spelling and see all possible meanings/translations it could have. All different meanings are lumped together with spelling as the key.  Is there some reason why variants of translation have to be stored separately?

**Comment by m-cote** [comment]
I made a follow up to the example above.
I created a new text "Text 1" with the content "This is test.". And I marked them as Well Known.
As a result these are the only words the user has in the database:
![image](https://user-images.githubusercontent.com/7547394/117344992-b9391300-aeae-11eb-9680-b718fc663570.png)

Then, I create another text "Text 2", that happens to contain the same words:
![image](https://user-images.githubusercontent.com/7547394/117345330-192fb980-aeaf-11eb-832b-097f1bd13936.png)
And when I click 'Save' and open Text 2, it turns out that only the first word has the status Well Known, but the other two are completely unknown and the counter says I have to process 2 words. But I expect all three to be in the status Well Known and the counter to say 0 words left.
![image](https://user-images.githubusercontent.com/7547394/117346023-e2a66e80-aeaf-11eb-9afe-70c2ec9ea612.png)

![image](https://user-images.githubusercontent.com/7547394/117345585-61e77280-aeaf-11eb-9d2c-5a10daa667da.png)

**Comment by m-cote** [comment]
> That's why I think it's better to keep the simple gross count of unknown words, because only counting words distinct by their spelling would give a false number: "kauftst', "kaufen" etc... are the same, they are not 2 different unknown words. And conversely, words written the same could have different meaning and so are different (especially in compound words).

I get it, it's a matter of personal preference. I would rather see a number of words left counting by the number of distinct spellings but ultimately it shouldn't matter either way.

**Comment by gustavklopp** [comment]
Finally it's a good idea to display only non-duplicate words in the 'TODO': it's always more motivating! so I've implemented it (in the texts list also)
I've also fixed the bug in creating the text where the statuses are not updated as expected.
